import Footer from "./components/FooterComponent/Footer";
import Navbar from "./components/NavbarComponent/Navbar";
import { Provider } from "./components/ThemeProvider/Provider";
import "./globals.scss";
import { Poppins } from "next/font/google";

const poppins = Poppins({ subsets: ["latin"], weight:[
  "100", "200", "300", "400", "500", "600", "700", "800", "900"
] });

export const metadata = {
  title: "University Management App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={poppins.className}>
        <Provider>
          <Navbar />
          {children}
          <Footer/>
        </Provider>
      </body>
    </html>
  );
}
